config/routes.rb
Rails.application.routes.draw do
  
  post 'webhooks/uninstall'

  get 'preferences/index'

  get 'preferences/store'
  
  get 'home/payed'

  resources :shop_collections
  mount ShopifyApp::Engine, at: '/'
  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  root :to => 'home#index'
  

end

app/models/session_storage.rb
class SessionStorage
  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
end

app/models/shop_collection.rb
class ShopCollection < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShopifyApp::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout 'embedded_app'

  def index
   init_webhooks
   init_payment
   @charges = ShopifyAPI::RecurringApplicationCharge.all
   
  end
  
  def payed
    puts "Payed action started"
    charge = ShopifyAPI::RecurringApplicationCharge.find(params[:charge_id])
    
    shop = Shop.find_or_initialize_by(shopify_domain: ShopifyAPI::Shop.current.domain)
    puts charge.status
    
    if charge.status == "accepted" || charge.status == "pending" 
      shop.shopify_reccuring_charge_id = params[:charge_id]
      puts "Payed action accepted and saved"
      
    else
      puts "Payed action not accepted and saved"
      shop.shopify_reccuring_charge_id = nil
    end
    
    shop.save!
    puts "Payed action end"
    
    redirect_to("http://#{DOMAIN_NAME}/")
  end
  
  def init_webhooks
    begin
     webhook = ShopifyAPI::Webhook.create(:format => "json", :topic => "app/uninstalled", :address => "http://#{DOMAIN_NAME}/webhooks/uninstall")
     raise "Webhook invalid: #{webhook.errors}" unless webhook.valid?
    rescue => ex
      puts ex.message
    
    end
  end 

  def init_payment
    begin
      puts "Starting the payment process"
      shop = Shop.find_or_initialize_by(shopify_domain: ShopifyAPI::Shop.current.domain)
      raise "Shop invalid: #{shop.errors}" unless shop.valid?
      puts "Found Shop"
      
      if shop.shopify_reccuring_charge_id.nil? || shop.shopify_reccuring_charge_id.empty?
        puts "Na payment yet, making it happen"              
        price = 20.0
        plan_name = ShopifyAPI::Shop.current.plan_name
        
        if plan_name == "basic" 
          price = 10.0
        end
        
        puts "Found plan"
        charge = ShopifyAPI::RecurringApplicationCharge.create({:name => "Standard Plan", :price => price, :trial_days => 7, :test => true, :return_url => "http://#{DOMAIN_NAME}/home/payed"})
        raise "Charge invalid: #{charge.errors}" unless charge.valid?
        redirect_to(charge.confirmation_url)
      end     
    rescue => ex
      puts ex.message    
    end
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  def index
  end

  def store
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ShopifyApp::SessionsController
end

app/controllers/shop_collections_controller.rb
class ShopCollectionsController < ApplicationController
  before_action :set_shop_collection, only: [:show, :edit, :update, :destroy]
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  layout 'embedded_app'

  # GET /shop_collections
  # GET /shop_collections.json
  def index
    @shop_collections = ShopCollection.all
  end

  # GET /shop_collections/1
  # GET /shop_collections/1.json
  def show
    
  end

  # GET /shop_collections/new
  def new
    @shop_collection = ShopCollection.new
    
  end

  # GET /shop_collections/1/edit
  def edit
    
  end

  # POST /shop_collections
  # POST /shop_collections.json
  def create
    @shop_collection = ShopCollection.new(shop_collection_params)

    respond_to do |format|
      if @shop_collection.save
        format.html { redirect_to @shop_collection, notice: 'Shop collection was successfully created.' }
        format.json { render :show, status: :created, location: @shop_collection }
      else
        format.html { render :new }
        format.json { render json: @shop_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_collections/1
  # PATCH/PUT /shop_collections/1.json
  def update
    respond_to do |format|
      if @shop_collection.update(shop_collection_params)
        format.html { redirect_to @shop_collection, notice: 'Shop collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_collection }
      else
        format.html { render :edit }
        format.json { render json: @shop_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_collections/1
  # DELETE /shop_collections/1.json
  def destroy
    @shop_collection.destroy
    respond_to do |format|
      format.html { redirect_to shop_collections_url, notice: 'Shop collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_collection
      @shop_collection = ShopCollection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_collection_params
      params.require(:shop_collection).permit(:name, :shop_collection_id, :autofill, :sort_field, :sort_order, :instock_only, :checked_at)
    end
end

app/controllers/webhooks_controller.rb
require 'base64'
require 'openssl'
    
class WebhooksController < ApplicationController
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  
  def uninstall
    connect_to_store
    
    shop = Shop.find_or_initialize_by(shopify_domain: ShopifyAPI::Shop.current.domain)
    charge = ShopifyAPI::RecurringApplicationCharge.find(shop.shopify_reccuring_charge_id)
    charge.delete
    shop.shopify_reccuring_charge_id = nil
    shop.save!
    puts "shop payment removed"
        
  end
  
  def verifiy_webhook
    data = env["HTTP_X_SHOPIFY_HMAC_SHA256"]
    digest  = OpenSSL::Digest::Digest.new('sha256')
    val = OpenSSL::HMAC.digest(digest, ShopifyApp.configuration.secret, data)
    calculated_hmac = Base64.encode64(val).strip
    
    calculated_hmac == data
  end
  
  def product_new
      data = ActiveSupport::JSON.decode(request.body.read)
      shopify_product_id = data["id"]

      Product.new_from_shopify(@s, shopify_product_id)

      head :ok
    end

    private

    def connect_to_store

      shop_url = request.headers['HTTP_X_SHOPIFY_SHOP_DOMAIN']
      @s = Shop.find_or_initialize_by(shopify_domain: shop_url)

      session = ShopifyAPI::Session.new(@s.shopify_domain, @s.shopify_token)
      session.valid?
      ShopifyAPI::Base.activate_session(session)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/shop_collections_helper.rb
module ShopCollectionsHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/home/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Home",
      icon: "<%= asset_path('faveicon.png') %>"
    });
  });
</script>
<h3>Product Categoriser & Custom Ordering App</h3>

<div id="app-wrapper">
	<div id="app-main-menu">
		<div class="menu-item active"><a href="#">Home</a></div>
		<div class="menu-item"><a href="/shop_collections">Collections Setup</a></div>
		<div class="menu-item"><a href="#">View Product stats</a></div>
		<div class="menu-item"><a href="/preferences">Options</a></div>		
	</div>
</div>


<div>
<% @charges.each do |charge| %>
	<br /><br />
	NEW Charge
	<br />
    <%= debug charge %>
<% end %>
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppOne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Categoriser & Orderer</title>

  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "<%= ShopifyApp.configuration.api_key %>",
      shopOrigin: '<%= "https://#{ @shop_session.url }" if @shop_session %>'
    });
  </script>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/preferences/index.html.erb
<h1>Preferences#index</h1>
<p>Find me in app/views/preferences/index.html.erb</p>

app/views/preferences/store.html.erb
<h1>Preferences#store</h1>
<p>Find me in app/views/preferences/store.html.erb</p>

app/views/shop_collections/_form.html.erb
<%= form_for(@shop_collection) do |f| %>
  <% if @shop_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_collection.errors.count, "error") %> prohibited this shop_collection from being saved:</h2>

      <ul>
      <% @shop_collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field hidden">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shop_collection_id %><br>
    <%#= f.select :shop_collection_id, @shopify_collections.map{|item| [item["title"], item["id"]] } %>
    <%#= f.select :shop_collection_id, @shopify_collections.map{|item| [item.title, item.id] } %>

  </div>
  <div class="field">
    <%= f.label :autofill %><br>
    <%= f.check_box :autofill %>
  </div>
  <div class="field">
    <%= f.label :sort_field %><br>
    <%= f.text_field :sort_field %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br>
    <%= f.text_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :instock_only %><br>
    <%= f.check_box :instock_only %>
  </div>
  <div class="field hidden">
    <%= f.label :checked_at %><br>
    <%= f.datetime_select :checked_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shop_collections/edit.html.erb
<h1>Editing Shop Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop_collection %> |
<%= link_to 'Back', shop_collections_path %>

app/views/shop_collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shop Collections</h1>
<!--<h1><%= "Environment: #{Rails.env}" %></h1>-->

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shop collection</th>
      <th>Autofill</th>
      <th>Sort field</th>
      <th>Sort order</th>
      <th>Instock only</th>
      <th>Checked at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_collections.each do |shop_collection| %>
      <tr>
        <td><%= shop_collection.name %></td>
        <td><%= shop_collection.shop_collection_id %></td>
        <td><%= shop_collection.autofill %></td>
        <td><%= shop_collection.sort_field %></td>
        <td><%= shop_collection.sort_order %></td>
        <td><%= shop_collection.instock_only %></td>
        <td><%= shop_collection.checked_at %></td>
        <td><%= link_to 'Show', shop_collection %></td>
        <td><%= link_to 'Edit', edit_shop_collection_path(shop_collection) %></td>
        <td><%= link_to 'Destroy', shop_collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop collection', new_shop_collection_path %>

app/views/shop_collections/new.html.erb
<h1>New Shop Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_collections_path %>

app/views/shop_collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop_collection.name %>
</p>

<p>
  <strong>Shop collection:</strong>
  <%= @shop_collection.shop_collection_id %>
</p>

<p>
  <strong>Autofill:</strong>
  <%= @shop_collection.autofill %>
</p>

<p>
  <strong>Sort field:</strong>
  <%= @shop_collection.sort_field %>
</p>

<p>
  <strong>Sort order:</strong>
  <%= @shop_collection.sort_order %>
</p>

<p>
  <strong>Instock only:</strong>
  <%= @shop_collection.instock_only %>
</p>

<p>
  <strong>Checked at:</strong>
  <%= @shop_collection.checked_at %>
</p>

<%= link_to 'Edit', edit_shop_collection_path(@shop_collection) %> |
<%= link_to 'Back', shop_collections_path %>

app/views/webhooks/uninstall.html.erb
<h1>Webhooks#uninstall</h1>
<p>Find me in app/views/webhooks/uninstall.html.erb</p>